### ISSUE TITLE
Any chance of this package being updated?

### ISSUE THREAD

**Issue by i001962** [noctisatrae/farsign#2]
Any chance of this package being updated?
Currently not working.

**Comment by noctisatrae** [comment]
Hey! It's one of my projects right now, I just need some time, the API changes were more significant than I thought.

**Comment by noctisatrae** [comment]
I'll leave this open for further discussion if we need ;)

**Comment by noctisatrae** [comment]
Large portions of work has been done now, and I can confidently say that I'm soon ready for a release! Marking this as resolved. :)
